version: '2'
services:
    php:
        build: ./docker
        volumes:
          - ".:/var/www/html"
        ports:
            - 8083:80
    db:
      image: mysql:5.6
      volumes:
        - "./docker/.data/db:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ugkagis
